### ISSUE TITLE
Issue with Cocoapods

### ISSUE THREAD

**Issue by Dubickiy** [kishikawakatsumi/BitcoinKit#44] opened 2018-03-27 16:06 UTC
Hello, @kishikawakatsumi 
I would like to install your library, but have problem with installing by cocoapods.

Here is error which I have get after **pod install**

[!] /bin/bash -c 
set -e
sh setup/build_libraries.sh

++ dirname setup/build_libraries.sh
+ SCRIPT_DIR=setup
+ cd setup
+ sh build_secp256k1.sh
++ dirname build_secp256k1.sh
+ SCRIPT_DIR=.
++ mktemp -d
+ TDIR=/var/folders/fn/vxjk2qq566n44mcp2sg0qgph0000gn/T/tmp.UZNMtVVk
+ trap '{ cd - ; rm -rf /var/folders/fn/vxjk2qq566n44mcp2sg0qgph0000gn/T/tmp.UZNMtVVk; exit 255; }' SIGINT
+ cd /var/folders/fn/vxjk2qq566n44mcp2sg0qgph0000gn/T/tmp.UZNMtVVk
+ git clone https://github.com/bitcoin-core/secp256k1.git src
Cloning into 'src'...
++ pwd
+ CURRENTPATH=/var/folders/fn/vxjk2qq566n44mcp2sg0qgph0000gn/T/tmp.UZNMtVVk
+ TARGETDIR_IPHONEOS=/var/folders/fn/vxjk2qq566n44mcp2sg0qgph0000gn/T/tmp.UZNMtVVk/.build/iphoneos
+ mkdir -p /var/folders/fn/vxjk2qq566n44mcp2sg0qgph0000gn/T/tmp.UZNMtVVk/.build/iphoneos
+ TARGETDIR_SIMULATOR=/var/folders/fn/vxjk2qq566n44mcp2sg0qgph0000gn/T/tmp.UZNMtVVk/.build/iphonesimulator
+ mkdir -p /var/folders/fn/vxjk2qq566n44mcp2sg0qgph0000gn/T/tmp.UZNMtVVk/.build/iphonesimulator
+ cd src
+ ./autogen.sh
./autogen.sh: line 3: autoreconf: command not found

If you met this error, could you please explain me solution of that problem

Thanks

Regards

**Comment by kishikawakatsumi** [comment] 2018-03-27 16:13
@Dubickiy Duplicate of https://github.com/kishikawakatsumi/BitcoinKit/issues/42 . BitcoinKit builds secp256k1 and OpenSSL itself for security reasons. They requires autoconf and automake. Please install them. `brew install autoconf automake` or use carthage. Carthage uses pre-built binary by default.

**Closed by kishikawakatsumi** 2018-03-27 16:13 UTC

**Comment by Dubickiy** [comment] 2018-03-27 16:15
Thanks for quick answer! Good luck

**Comment by Smiacter** [comment] 2018-04-24 12:52
`[!] /bin/bash -c
set -e
sh setup/build_libraries.sh

: putting auxiliary files in '.'.
: copying file './ltmain.sh'
++ dirname setup/build_libraries.sh
+ SCRIPT_DIR=setup
+ cd setup
+ sh build_secp256k1.sh
++ dirname build_secp256k1.sh
+ SCRIPT_DIR=.
++ mktemp -d
+ TDIR=/var/folders/zq/ztvlzr7539sdkhgx08h75nr00000gn/T/tmp.8QHwOnHz
+ trap '{ cd - ; rm -rf /var/folders/zq/ztvlzr7539sdkhgx08h75nr00000gn/T/tmp.8QHwOnHz; exit 255; }' SIGINT
+ cd /var/folders/zq/ztvlzr7539sdkhgx08h75nr00000gn/T/tmp.8QHwOnHz
+ git clone https://github.com/bitcoin-core/secp256k1.git src
Cloning into 'src'...
++ pwd
+ CURRENTPATH=/var/folders/zq/ztvlzr7539sdkhgx08h75nr00000gn/T/tmp.8QHwOnHz
+ TARGETDIR_IPHONEOS=/var/folders/zq/ztvlzr7539sdkhgx08h75nr00000gn/T/tmp.8QHwOnHz/.build/iphoneos
+ mkdir -p /var/folders/zq/ztvlzr7539sdkhgx08h75nr00000gn/T/tmp.8QHwOnHz/.build/iphoneos
+ TARGETDIR_SIMULATOR=/var/folders/zq/ztvlzr7539sdkhgx08h75nr00000gn/T/tmp.8QHwOnHz/.build/iphonesimulator
+ mkdir -p /var/folders/zq/ztvlzr7539sdkhgx08h75nr00000gn/T/tmp.8QHwOnHz/.build/iphonesimulator
+ cd src
+ ./autogen.sh
/usr/local/bin/glibtoolize: line 406: /usr/local/Library/ENV/4.3/sed: No such file or directory
/usr/local/bin/glibtoolize: line 2513: /usr/local/Library/ENV/4.3/sed: No such file or directory
/usr/local/bin/glibtoolize: line 2513: /usr/local/Library/ENV/4.3/sed: No such file or directory
/usr/local/bin/glibtoolize: line 3601: /usr/local/Library/ENV/4.3/sed: No such file or directory
/usr/local/bin/glibtoolize: line 3845: /usr/local/Library/ENV/4.3/sed: No such file or directory
/usr/local/bin/glibtoolize: line 861: /usr/local/Library/ENV/4.3/sed: No such file or directory
/usr/local/bin/glibtoolize: line 3771: /usr/local/Library/ENV/4.3/sed: No such file or directory
configure.ac:10: installing 'build-aux/compile'
configure.ac:5: installing 'build-aux/config.guess'
configure.ac:5: installing 'build-aux/config.sub'
configure.ac:9: installing 'build-aux/install-sh'
configure.ac:10: error: required file 'build-aux/ltmain.sh' not found
configure.ac:9: installing 'build-aux/missing'
Makefile.am: installing 'build-aux/depcomp'
parallel-tests: installing 'build-aux/test-driver'
autoreconf: automake failed with exit status: 1`

I have installed autoconf automake, but still occur error. @kishikawakatsumi

**Comment by GyusongMoon** [comment] 2019-03-26 07:24
same issue too..

**Comment by ghost** [comment] 2019-10-28 05:12
same issue too..
