### ISSUE TITLE
Problems with pod install

### ISSUE THREAD

**Issue by hoanglu14** [kishikawakatsumi/BitcoinKit#52] opened 2018-06-06 02:52 UTC
Hi there,

I'm having a problem installing this framework via CocoaPods

<img width="705" alt="screen shot 2018-06-06 at 9 51 38 am" src="https://user-images.githubusercontent.com/39908401/41013221-411943ea-696f-11e8-9bbd-ce3777cd7802.png">

I have tried to reinstall autoconf and automake but no luck. Any idea?

**Comment by OleksiiShulzhenko** [comment] 2018-06-06 08:33
I have the same problem.

**Comment by Jax1993** [comment] 2018-06-06 09:20
Duplicate of #42 . BitcoinKit builds secp256k1 and OpenSSL itself for security reasons. They requires autoconf and automake. Please install them. brew install autoconf automake or use carthage. Carthage uses pre-built binary by default. @hoanglu14  @OleksiiShulzhenko

**Comment by OleksiiShulzhenko** [comment] 2018-06-06 09:42
@Jax1993 
<img width="1628" alt="2018-06-06 12 40 02" src="https://user-images.githubusercontent.com/22858812/41030410-f404c9ae-6986-11e8-84c2-de593dbe4276.png">
<img width="1680" alt="2018-06-06 12 41 08" src="https://user-images.githubusercontent.com/22858812/41030419-fc3f67b4-6986-11e8-999b-ac46fbdeebdf.png">

**Comment by Jax1993** [comment] 2018-06-06 10:10
**When you have a problem, you should google it first. ...**
"xcrun: error: SDK "iphonesimulator" cannot be located".
Update your Xcode and Open in Xcode Preferences, tab into Locations and take a look at your Command Line Tools selection.

**Comment by hoanglu14** [comment] 2018-06-06 18:01
Thanks @Jax1993 for the fast response but I did mentioned I haved installed autoconf and automake and still have the same error.

**Comment by Gensun** [comment] 2018-06-11 10:21
sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer/

**Closed** 2018-06-26 13:39 UTC

**Comment by DiwakarThapa** [comment] 2019-01-23 08:04
How to solve this issue ? 
[!] /bin/bash -c
set -e
sh setup/build_libraries.sh

glibtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
glibtoolize: copying file 'build-aux/ltmain.sh'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'build-aux/m4'.
glibtoolize: copying file 'build-aux/m4/libtool.m4'
glibtoolize: copying file 'build-aux/m4/ltoptions.m4'
glibtoolize: copying file 'build-aux/m4/ltsugar.m4'
glibtoolize: copying file 'build-aux/m4/ltversion.m4'
glibtoolize: copying file 'build-aux/m4/lt~obsolete.m4'
checking build system type...
++ dirname setup/build_libraries.sh
+ SCRIPT_DIR=setup
+ cd setup
+ sh build_secp256k1.sh
++ dirname build_secp256k1.sh
+ SCRIPT_DIR=.
++ mktemp -d
+ TDIR=/var/folders/mt/t76q4w_901l80sqh4000dckm0000gn/T/tmp.D6imaNi4
+ trap '{ cd - ; rm -rf /var/folders/mt/t76q4w_901l80sqh4000dckm0000gn/T/tmp.D6imaNi4; exit 255; }' SIGINT
+ cd /var/folders/mt/t76q4w_901l80sqh4000dckm0000gn/T/tmp.D6imaNi4
+ git clone https://github.com/bitcoin-core/secp256k1.git src
Cloning into 'src'...
++ pwd
+ CURRENTPATH=/var/folders/mt/t76q4w_901l80sqh4000dckm0000gn/T/tmp.D6imaNi4
+ TARGETDIR_IPHONEOS=/var/folders/mt/t76q4w_901l80sqh4000dckm0000gn/T/tmp.D6imaNi4/.build/iphoneos
+ mkdir -p /var/folders/mt/t76q4w_901l80sqh4000dckm0000gn/T/tmp.D6imaNi4/.build/iphoneos
+ TARGETDIR_SIMULATOR=/var/folders/mt/t76q4w_901l80sqh4000dckm0000gn/T/tmp.D6imaNi4/.build/iphonesimulator
+ mkdir -p /var/folders/mt/t76q4w_901l80sqh4000dckm0000gn/T/tmp.D6imaNi4/.build/iphonesimulator
+ cd src
+ ./autogen.sh
configure.ac:10: installing 'build-aux/compile'
configure.ac:5: installing 'build-aux/config.guess'
configure.ac:5: installing 'build-aux/config.sub'
configure.ac:9: installing 'build-aux/install-sh'
configure.ac:9: installing 'build-aux/missing'
Makefile.am: installing 'build-aux/depcomp'
parallel-tests: installing 'build-aux/test-driver'
+ cd src
++ xcrun -find clang
++ xcrun -sdk iphonesimulator --show-sdk-path
++ xcrun -find clang++
++ xcrun -sdk iphonesimulator --show-sdk-path
+ ./configure --host=x86_64-apple-darwin CC=/Applications/Xcode 2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang 'CFLAGS=-O3 -arch i386 -arch x86_64 -isysroot /Applications/Xcode 2.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk -fembed-bitcode-marker -mios-simulator-version-min=8.0' CXX=/Applications/Xcode 2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ 'CXXFLAGS=-O3 -arch i386 -arch x86_64 -isysroot /Applications/Xcode 2.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk -fembed-bitcode-marker -mios-simulator-version-min=8.0' --prefix=/var/folders/mt/t76q4w_901l80sqh4000dckm0000gn/T/tmp.D6imaNi4/.build/iphoneos
configure: WARNING: you should use --build, --host, --target
configure: WARNING: invalid host type: 2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
configure: WARNING: you should use --build, --host, --target
configure: WARNING: invalid host type: 2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
Invalid configuration `2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang': machine `2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang' not recognized
configure: error: /bin/sh build-aux/config.sub 2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed
